### PR TITLE
Generate version.h file

### PR DESCRIPTION
**Pull request by waterkip**
** PR remark only
My CMake skills are not that good, I've tried adding the version.h generation in the CMakeList.txt, but I failed. Adding it to the Makefile was the easier solution.
**

In order to prevent weird version discussions (see #481 for such an
example) this changeset tries to do versioning the same way as the git
project does this.

Some caveats apply:

  1) Maintainers *must* use annotated tags. Release 1.3.1 is not
     annotated for example.

  2) Maintainers *must* can use a `version` file in the repo to override
     any logic. This will generate a "static" version.

  3) Maintainers *must* bump the version in `LASTPASS-VERSION-GEN` after
     a release.

Some benefits apply too:

  1) We can see clearly at which version the client was build
  2) We can see if it was a "dirty" build

   ```
   $ lpass --version
   LastPass CLI v1.3.0.34.g5bf38bc.dirty
   ```

Signed-off-by: Wesley Schwengle <wesley@schwengle.net>

### CODE REVIEW

**Comment by GPaulovics** [comment]
I really like the idea. And I'll try to keep in mind that I'll have to bump the version. Thank You @waterkip.

**Comment by eli-schwartz** [comment]
>  My CMake skills are not that good, I've tried adding the version.h generation in the CMakeList.txt, but I failed. Adding it to the Makefile was the easier solution.

Easier, but ultimately doesn't work. :(

#490 

Furthermore, the actual script itself doesn't really work, since it recompiles version.h every time you run it, thus causing lots of files to be rebuilt. And it gets run every time you run the toplevel make, even just to run `make && sudo make install`.
It works for the git project, because the git project is using a different format which this adapted script is also trying to use, which is *not* a C header but a Makefile include fragment.

This broke https://github.com/eli-schwartz/pkgbuilds/pull/12

**Comment by waterkip** [comment]
I'm sorry it broke your thing. I agree with the make stuff, but not every make invocation should not rebuild the sources. `make install` should just copy the build artifacts to the correct location IMO.

**Comment by eli-schwartz** [comment]
Well, make invocations typically have the install target depend on the sources being properly built -- they're just not supposed to rebuild them if they're already built. And that is what one of my commits fixed. :)

**Pull request merged**
