### PR TITLE
add-json-minified-lpass-ls-argument

### LINKED ISSUE #560: JSON output for lpass ls
Hi,

it would be great to have json output for the account list, to be able to more easily parse it in scripts. The current textual format is a bit painful

Example format that would be good for my needs:
```json
[
  {
    "id": 123123123123,
    "name": "the name of the account",
    "type": "password",
    "path": ["Shared folder", "subfolder", "subsubfolder"],
    "pathString": "Shared folder/subfolder/subsubfolder"
  }
]
```

### PR DESCRIPTION
**Pull request by Lou486**
Added an option to allow lpass ls to output in minified JSON. 

Closes #560

### CODE REVIEW

**Comment by 0xdevalias** [comment]
This can be used with homebrew like follows:

```bash
⇒ brew edit lastpass-cli
```

Add the following:

```ruby
  # JSON Minified Support: https://github.com/lastpass/lastpass-cli/pull/572
  patch do
    url "https://github.com/lastpass/lastpass-cli/pull/572/commits/1142db12cb774ed58328e567412c0727485a3b42.patch?full_index=1"
    sha256 ""
  end
```

```
⇒  brew uninstall lastpass-cli

⇒  brew install --build-from-source lastpass-cli
```

**Comment by 0xdevalias** [comment]
@mateusmartins-lp It's good 'open source courtesy' to give context when closing an issue/PR, not just closing it with no explanation.

**Comment by 0xdevalias** [comment]
> > @mateusmartins-lp It's good 'open source courtesy' to give context when closing an issue/PR, not just closing it with no explanation.
> 
> Hello @0xdevalias. The Pull Requests were closed unintentionally. By tomorrow I will be sure to leave a message on how to proceed. My sincere apologies for the inconvenience.
> 
> _Originally posted by @mateusmartins-lp in https://github.com/lastpass/lastpass-cli/issues/553#issuecomment-2098844351_

**Comment by mateusmartins-lp** [comment]
Regrettably, your PR submission was unintentionally closed during an operation, before we could complete our review and respond accordingly. Unable to revert it to 'Open' status, we invite you to resubmit your contribution at your earliest convenience. We apologize for this mishap. Rest assured, we value all contributions and remain dedicated to providing transparency and closure to the community. Thank you for your understanding.

**Pull request closed without merging**
