### PR TITLE
use http 1.1

### PR DESCRIPTION
**Pull request by tod**
On Ubuntu 22.10 I would get an error: 

Error: Stream error in the HTTP/2 framing layer.

After some google searching and looking at logs, it appears to be a new version of libcurl and this patch makes it work. I'm not sure if this is the best way, I just know it works on my machine.

### CODE REVIEW

**Comment by taylorreece** [comment]
Hey @tod - I was hitting this same error today on MacOS. FWIW (different OS, I know), bumping `lpass` from 1.3.3 to 1.3.4 solved the problem for me.

**Comment by tod** [comment]
I don't think 1.3.4 fixed it for me.

**Comment by sverhagen** [comment]
1.3.4 is where the problem existed for me too. I came here to share my fix, and it's exactly the same solution as posted in this merge request. Just take that as a data point, i.e. someone tested it :wink: I'm on Ubuntu 22.10, and the issue started maybe about a week ago.

**Comment by austinbutler** [comment]
Bumping to 1.3.4 worked for me on NixOS as well.

**Comment by boginw** [comment]
Just to pitch in, I'm on Ubuntu 22.10, and with the CLI on version 1.3.4-1.GIT, I still receive: `Error: Stream error in the HTTP/2 framing layer.`

**Comment by mateusmartins-lp** [comment]
Regrettably, your PR submission was unintentionally closed during an operation, before we could complete our review and respond accordingly. Unable to revert it to 'Open' status, we invite you to resubmit your contribution at your earliest convenience. We apologize for this mishap. Rest assured, we value all contributions and remain dedicated to providing transparency and closure to the community. Thank you for your understanding.

**Pull request closed without merging**
