### PR TITLE
Adjust regex to work on macOS

### PR DESCRIPTION
**Pull request by ellio167**

### CODE REVIEW

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/lastpass/lastpass-cli/pull/632

**Comment by 0xdevalias** [comment]
@mateusmartins-lp It's good 'open source courtesy' to give context when closing an issue/PR, not just closing it with no explanation.

**Comment by 0xdevalias** [comment]
> The Pull Requests were closed unintentionally. By tomorrow I will be sure to leave a message on how to proceed.

@mateusmartins-lp Ah true, thanks for clarifying. Sounds good :)

**Comment by 0xdevalias** [comment]
> > @mateusmartins-lp It's good 'open source courtesy' to give context when closing an issue/PR, not just closing it with no explanation.
> 
> Hello @0xdevalias. The Pull Requests were closed unintentionally. By tomorrow I will be sure to leave a message on how to proceed. My sincere apologies for the inconvenience.
> 
> _Originally posted by @mateusmartins-lp in https://github.com/lastpass/lastpass-cli/issues/553#issuecomment-2098844351_

**Comment by mateusmartins-lp** [comment]
Regrettably, your PR submission was unintentionally closed during an operation, before we could complete our review and respond accordingly. Unable to revert it to 'Open' status, we invite you to resubmit your contribution at your earliest convenience. We apologize for this mishap. Rest assured, we value all contributions and remain dedicated to providing transparency and closure to the community. Thank you for your understanding.

**Pull request closed without merging**
