### PR TITLE
Fix #464

### LINKED ISSUE #464: Unable to add the group to a shared folder
Hi,
I am not able to add the group to a shared folder via lpass cli, getting the following error:

Error: Unable to encrypt sharing key with pubkey (-1)

But able to add it via UI.

Can you please help us in fixing the issue ?

command used: lpass share useradd <group_name>

### PR DESCRIPTION
**Pull request by jonathanlking**
This is an attempt to allow folders to be shared with groups that contain members without public/sharing keys and will fix #464.
For such users we make a slightly different request, as used by the browser extension.

Running the command appears to add these groups correctly, and the users without public keys are able to access the passwords.

### CODE REVIEW

**Comment by GPaulovics** [comment]
Hey @jonathanlking 
Thank you for your contribution.
Could you please sign off your commit, as stated in [https://github.com/lastpass/lastpass-cli/blob/master/CONTRIBUTING](url), so i can merge it.

Thank You.

**Comment by FloraMina** [comment]
Hi @jonathanlking
 
We are facing the exact same issue as you did - I would greatly appreciate if you could sign off your PR so that it can be integrated in the next lastpass-cli release.

Cheers !

**Comment by jonathanlking** [comment]
Hi, apologies for taking so long to sign off the commit.

I want to add the disclaimer that although this worked for me last year (April-June 2019), I have not tested it recently. Additionally this fix was discovered through looking at the implementation of the browser extension, rather than any publicly available documentation.

**Comment by FloraMina** [comment]
Thanks a lot for everything @jonathanlking !

**Comment by mateusmartins-lp** [comment]
Regrettably, your PR submission was unintentionally closed during an operation, before we could complete our review and respond accordingly. Unable to revert it to 'Open' status, we invite you to resubmit your contribution at your earliest convenience. We apologize for this mishap. Rest assured, we value all contributions and remain dedicated to providing transparency and closure to the community. Thank you for your understanding.

**Pull request closed without merging**
