### PR TITLE
Bump version to 1.3.2

### PR DESCRIPTION
**Pull request by waterkip**
The git repo contains the latest release which will be 1.3.2. This makes
it easier for others to install the sources from git and know that they
aren't running the previous version.

Signed-off-by: Wesley Schwengle <wesley@schwengle.net>

### CODE REVIEW

**Comment by rutkai** [comment]
What is the point of this version bump? The latest version is 1.3.1 and there were no commits since then.

**Comment by waterkip** [comment]
The point is that when I make a change in my repo and/or update anything, and I hit make install I have the same version as someone who checks out the tag v1.3.1, which is incorrect. The repo should contain (IMO) the newest version, not the one that was just released.

**Comment by rutkai** [comment]
That's logical, we don't know which version is going to be released under the next tag though. If we merge a new feature, then it's going to be `1.4.0` instead of `1.3.2` but as it's the master, I think we can live with this.

**Comment by waterkip** [comment]
With a new feature you can always bump the version to something new after the merge of the new feature. But I want to prevent showing `lpass --version` to give me a tagged version on development.

**Comment by rutkai** [comment]
Fair enough ;)

**Pull request merged**
