### PR TITLE
Add link to documentation

### PR DESCRIPTION
**Pull request by StevenLiekens**

### CODE REVIEW

**Comment by bcopeland** [comment]
Looks fine but could you add Signed-off-by?  (Please see CONTRIBUTING file).

**Comment by StevenLiekens** [comment]
No problem. Assuming that my commit doesn't violate any terms. I copied the text and link from a helpdesk page.
https://helpdesk.lastpass.com/lastpass-command-line-application/

**Comment by bcopeland** [comment]
No it is fine.  So can I take your comment as assent to the certificate of origin?  I can just add my own signed-off-by to the commit log if yes, and if that makes things easier.

**Comment by StevenLiekens** [comment]
@bcopeland I amended my commit message. Sorry for letting you wait. I didn't have time to do it earlier.

**Comment by bcopeland** [comment]
Perfect - no, wasn't in a hurry; I just didn't understand if you intended to send an update or were just saying "I'm okay with that" :)

**Comment by StevenLiekens** [comment]
Sorry for the confusion. Thanks for merging!

**Pull request merged**
