### PR TITLE
Update askpass prompt to use more explicit message

### PR DESCRIPTION
**Pull request by ovv**
My goal is to integrate lpass with kwallet. In order to do so a more explicit prompt message including the account is useful.

### CODE REVIEW

**Comment by 41m332** [comment]
test comment

**Comment by 41m332** [comment]
checking extension active does not stop commenting.

**Comment by lgaldamez13** [comment]
Test comment

**Comment by lgaldamez13** [comment]
Test

**Comment by mateusmartins-lp** [comment]
Regrettably, your PR submission was unintentionally closed during an operation, before we could complete our review and respond accordingly. Unable to revert it to 'Open' status, we invite you to resubmit your contribution at your earliest convenience. We apologize for this mishap. Rest assured, we value all contributions and remain dedicated to providing transparency and closure to the community. Thank you for your understanding.

**Pull request closed without merging**
