### PR TITLE
Fix help width

### PR DESCRIPTION
**Pull request by cjac**
Improve help readability
    
    * set some tabs
    * insert newlines

### CODE REVIEW

**Comment by bcopeland** [comment]
Thanks for the PR - all the changes look fine but I'll need signed-off-by to apply them, can you resend?  (see CONTRIBUTING file).

**Comment by cjac** [comment]
Okay!  Commit made with -s

**Comment by bcopeland** [comment]
So I still can't figure out which commits to take here.  dac74e49de02e397a7d9bd25d8099f7a82dae5e5 has the s-o-b, so that's good, but 97157f1788e54e49fbe88777f703ee82fbb6e4c2 is the tip of the branch and does not, nor do any of the ancestor commits.  There are lots of merge commits that don't make much sense to me.  Ideally, I'd see maybe one or two non-merge commits here that applies on top of lastpass-cli master, each of which carry a signed-off-by.  Any chance you can git rebase -i d980299e2879d6995d8df5b25b99cef7480b1e6f and clean up the history a bit?

**Comment by bcopeland** [comment]
Closing on basis of previous comment.

**Pull request closed without merging**
