### PR TITLE
added lpass status command to query agent state

### PR DESCRIPTION
**Pull request by nickaknudson**
this command makes it a little easier to script with lpass

### CODE REVIEW

**Comment by bcopeland** [comment]
How does your script use this?  I'd like a little more information on the use-case.  Sync seems like a random place to put this, would it make sense to have a 'status' command to report agent status instead?

**Comment by cledoux** [comment]
Thanks @nickaknudson for adding this, I'm looking for very similar functionality.

For my use case, the  `lpass status` command suggested by @bcopeland makes more sense.

My use case is to check if lpass is logged in, and if not, automatically log in. I currently use `lpass ls &> /dev/null` and check the exit code. An `lpass status` command would make this much cleaner.

Some features of `lpass status` I would find useful:
* Set the exit code based on whether logged in or not.
  * 0 if logged in
  * >0 if not logged in.
*  'Quiet' option (-q | --quiet). If given, only set exit code and print no messages.

The two features above allow script commands like 

    if lpass status --quiet; then 
        do-something-if-logged-in
    fi

**Comment by nickaknudson** [comment]
Hey @bcopeland and @cledoux I went ahead and implemented `lpass status` as suggested.

**Comment by bcopeland** [comment]
Looks good, thanks!  We might want to add other stuff here at some point (such as pid agent is running on, number of unsynced queue items, etc.) but I think this is useful as-is so will merge it now.

**Pull request merged**
