### PR TITLE
Added support for multiple ids

### PR DESCRIPTION
**Pull request by AngusG**
<code> lpass show </code> accepts multiple ids as requested in https://github.com/lastpass/lastpass-cli/issues/118
Signed-off-by: Angus Galloway angustwitter@gmail.com

### CODE REVIEW

**Comment by bcopeland** [comment]
Thanks!

I'll take this patch but I want to change a few things first -- namely, I'm not sure it makes sense to do the 'Multiple matches found' thing if multiple ids are supplied (maybe we should always show all matches?), and similarly clipboard handling may not make sense as-is.

**Comment by bcopeland** [comment]
(Just to clarify, no work needed on your part, I can do this on top.)

**Comment by AngusG** [comment]
Good point, I think we should always show all matches. For example, in my vault I have multiple google accounts:

<code>Email</code>
<code>    accounts.google.com [id: ...7262]</code>
<code>    login.live.com [id: x]</code>
<code>    accounts.google.com (2) [id: ...7342]</code>
<code>    accounts.google.com [id: ....7892]</code>

(The (2) appears be for an old password that wasn't forgotten)

then

<code> >> lpass show accounts.google.com</code>
<code><b>Multiple matches found.</b></code>
<code>Email/accounts.google.com [id: ...7892]</code>
<code>Email/accounts.google.com [id: ...7262]</code>

I would rather just see all matching accounts.

**Comment by bcopeland** [comment]
Yes, I think what I'll do is to add a new switch to expand all matches, and then those who want it can add it to their alias for show and thus no longer see the 'Multiple matches' summary.  Also if multiple ids are supplied, just turn that switch on.

I started on this but it turns out I'll need to slightly rework ```search_accounts()``` to handle the case where an account is matched multiple times when multiple search criteria (i.e. more than one id) are supplied.

**Comment by bcopeland** [comment]
I merged this with some edits, thanks!

**Comment by AngusG** [comment]
Thanks, I like what you did with the switch. I was looking into the duplicate match when a user + id is provided, I had a feeling using multiple lists would be better than trying to hack up <code>search_accounts</code>, nice stuff! Also, I think you forgot to update<code> cmd_show_usage</code>, an easy one to miss.

**Comment by bcopeland** [comment]
Good catch, fixed now :)

**Pull request closed without merging**
