### PR TITLE
265-lpass-not-syncing

### PR DESCRIPTION
**Pull request by msbit**
Change per-job lockfile from:

  `${XDG_RUNTIME_DIR}/lpass/upload-queue/<timestamp>.lock`

to:

  `${XDG_RUNTIME_DIR}/lpass/upload-queue.<timestamp>.lock`

as the `${XDG_RUNTIME_DIR}/lpass/upload-queue` directory doesn't
exist.

Fixes https://github.com/lastpass/lastpass-cli/issues/265

Signed-off-by: Tom Sullivan <tom@msbit.com.au>

### CODE REVIEW

**Comment by msbit** [comment]
Not sure if this is something for you to look at @bcopeland, but you've been most active recently in the history for `upload-queue.c`. If not, could you let me know who'd be the best to tag?

**Comment by msbit** [comment]
Sorry about that, accidentally removed the wrong source branch.

**Comment by GPaulovics** [comment]
Well, the directory definitely should exist. ( See upload-queue.c - upload_queue_write_entry function ) 

Is it possible that the user running lpass does not have write access to the folder set in LPASS_HOME? ( Or where the config folder is set to )

**Comment by msbit** [comment]
> Well, the directory definitely should exist. ( See upload-queue.c - upload_queue_write_entry function )

Ah yes, I see where it creates the directory. I'll have to check to ensure that `make_upload_dir` is called in the codepath that seems to exhibit this issue.

> Is it possible that the user running lpass does not have write access to the folder set in LPASS_HOME? ( Or where the config folder is set to )

I'm fairly sure that the running user has filesystem permissions to create the appropriate directories, will have to check that also.

**Comment by msbit** [comment]
@GPaulovics I've taken a look at this again, to reacquaint myself with the problem.

The issue is that the upload queue directory is created, but the lockfile storage directory isn't, and then the subsequent creation of the lockfile itself fails.

The respective paths, as returned by `config_path` are:

```
config_path("upload_queue"):                     /home/tom/.local/share/lpass/upload_queue
config_path("upload-queue/15514988830000.lock"): /run/user/1000/lpass/upload-queue/15514988830000.lock
```

This output is with the following relevant environment variables set:

```
$ env | grep 'LPASS\|XDG'
XDG_SESSION_ID=8
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_RUNTIME_DIR=/run/user/1000
```

I think I'll take a look at where the `/run/user/1000/lpass` path is created for a guidance as to whether the fix could be to create the directory up front instead.

**Comment by msbit** [comment]
I've looked at creating the required directory before attempting to use it (effectively mirroring `make_upload_dir`) in https://github.com/msbit/lastpass-cli/commit/1f503493fd1f1b3c6e2605e4273f39cfc906401b.

Does anyone have a preference as to how to deal with this issue?

**Comment by GPaulovics** [comment]
@msbit 
What is your opinion about making the upload-queue folder and the lock files the same config type?

At this piece of code ( in config.h - config_type config_path_type(const char *name) function):
`if (strlen(name) >= 5 && !strcmp(name + strlen(name) - 5, ".lock")) {
    return CONFIG_RUNTIME;
}`

We could either filter that if the parameter name is "upload-queue" then it could be CONFIG_RUNTIME or just flagging the lock files to be CONFIG_DATA like the folder is right now.

I personally think both of them being CONFIG_RUNTIME makes more sense. But I'm happy either way.

**Comment by msbit** [comment]
> @msbit
> What is your opinion about making the upload-queue folder and the lock files the same config type?

I think it would be best to keep them separate, as the upload queue should be long lived, and the lock files short lived. `XDG_RUNTIME_DIR` is meant to be a [temporary location](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (cleaned up after logout, reboot etc), which helps clean out stale lock and pid files at the system level. The same behaviour wouldn't suit the upload queue.

If we wanted a more generalised solution to this issue, then `config_path_for_type` at https://github.com/lastpass/lastpass-cli/blob/c9c9d8f34453678a266a6fbfd64fdbf826c37538/config.c#L131 could be expanded to create the subdirectories required to satisfy the provided `name` path, in addition to the base `lpass` directory.

**Comment by GPaulovics** [comment]
You are right. ( I honestly was not aware of these rules with XDG folders so thank you for the link ) 

I would totally support expanding the config_path_for_type with creating subdirectories under the XDG_RUNTIME_DIR/lpass directory.

My only problem with the solution in this PR is that if we set an LPASS_HOME env variable we are just going to create lock files in the root of the LPASS_HOME directory. ( If I'm not mistaken ) 

And Thank You for your time working on this.

**Comment by msbit** [comment]
> I would totally support expanding the config_path_for_type with creating subdirectories under the XDG_RUNTIME_DIR/lpass directory.

I've put [something together](https://github.com/msbit/lastpass-cli/commit/8b630cb52c7b418ffe811df85313931a7d3a6c9c) to generalise creating necessary subdirectories (eg when calling something like `config_exists("upload-queue/15514988830000.lock")`). 

> My only problem with the solution in this PR is that if we set an LPASS_HOME env variable we are just going to create lock files in the root of the LPASS_HOME directory. ( If I'm not mistaken )

Yep, that is what will happen if the `LPASS_HOME` environment variable is set. Looking back at this PR, I think it was a bit of a naive hack to get this working, not especially thought out by me :)  Depending on how you feel about the patch I've linked above, I may replace the contents of this PR with that.

> And Thank You for your time working on this.

No problems :)

**Comment by GPaulovics** [comment]
I totally like your solution in the patch.

If you would replace the content of this PR, i would be happy to merge it. :) 

Thank You again. :)

**Comment by msbit** [comment]
@GPaulovics pushed up the contents of the patch, with the `while` replaced with a `for` to cleanup the preconditions a little.

Tested under Ubuntu bionic, running both `lpass add ...` and `lpass add --sync=no ...` then `lpass sync`, and the item is successfully uploaded.

**Comment by GPaulovics** [comment]
Awesome, thank you very much.

**Pull request merged**
